spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   #update   create-drop  create validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres
    hikari:
      schema: library_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS library_schema
      connection-timeout: 10000
server:
  port: 8080

app:
  redis:
    enable: true
  cache:
    cacheType: redis
    cache-names:
      - bookEntities
      - bookNameAuthor
      - bookByCategory
      - bookById
    caches:
      bookEntities:
        expiry: 10m
      bookNameAuthor:
        expiry: 10m
      bookByCategory:
        expiry: 10m
      bookById:
        expiry: 10m

