version: '3'

services:
  postegres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_db

  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"